name: Ansible CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate Ansible Inventory and Scan Host Keys
        working-directory: ./terraform/environments/${{ matrix.environment }}
        run: |
          terraform init

          VM_PUBLIC_IP=$(terraform output -raw vm_public_ip)

          ssh-keyscan -H $VM_PUBLIC_IP >> ~/.ssh/known_hosts

          terraform output -json ansible_inventory > ../../../ansible/inventory/${{ matrix.environment }}.inventory.json

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory/${{ matrix.environment }}.inventory.json playbooks/site.yml --extra-vars "ansible_sudo_pass=${{ secrets.SUDO_PASSWORD }}"
