- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{domain_name}}.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart nginx

- name: Enable nginx configuration
  file:
    src: /etc/nginx/sites-available/{{domain_name}}.conf
    dest: /etc/nginx/sites-enabled/{{domain_name}}.conf
    state: link

- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes
