---
- name: SSH Setup
  ansible.builtin.openssh_keypair:
    path: /etc/ssh/ssh_host_ecdsa_key
    type: ecdsa
    state: present

- name: Set permit root login to no
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd

- name: Set alternate SSH port in sshd_config
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port 22"
  notify: Restart sshd
