name: Ansible CI/CD

on:
  workflow_dispatch:

jobs:
  ansible-dev:
    name: "Ansible: Dev"
    runs-on: ubuntu-latest
    steps:
      - name: Generate Ansible Inventory
        working-directory: ./terraform/environments/dev
        run: |
          terraform init
          terraform output -json ansible_inventory > ../../../ansible/inventory/dev.inventory.json
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory/dev.inventory.json playbooks/site.yml

  ansible-staging:
    name: "Ansible: Staging"
    runs-on: ubuntu-latest
    needs: ansible-dev
    steps:
      - name: Generate Ansible Inventory
        working-directory: ./terraform/environments/staging
        run: |
          terraform init
          terraform output -json ansible_inventory > ../../../ansible/inventory/staging.inventory.json
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory/staging.inventory.json playbooks/site.yml

  ansible-prod:
    name: "Ansible: Prod"
    runs-on: ubuntu-latest
    needs: ansible-staging
    steps:
      - name: Generate Ansible Inventory
        working-directory: ./terraform/environments/prod
        run: |
          terraform init
          terraform output -json ansible_inventory > ../../../ansible/inventory/prod.inventory.json
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory/prod.inventory.json playbooks/site.yml
