name: "Terraform Configuration Drift Detection"

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  drift-dev:
    name: "Drift Check: Dev"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          client-secret: ${{ env.ARM_CLIENT_SECRET }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev
      - name: Detect Drift (Plan)
        id: tf-plan
        run: |
          terraform plan -detailed-exitcode -no-color || export exitcode=$?
          if [ -z "$exitcode" ]; then
            exit 0
          elif [ $exitcode -eq 2 ]; then
            echo "::error::Drift detected in Dev environment!"
            exit 1
          fi
        working-directory: ./terraform/environments/dev

  drift-staging:
    name: "Drift Check: Staging"
    needs: drift-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          client-secret: ${{ env.ARM_CLIENT_SECRET }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/staging
      - name: Detect Drift (Plan)
        id: tf-plan
        run: |
          terraform plan -detailed-exitcode -no-color || export exitcode=$?
          if [ -z "$exitcode" ]; then
            exit 0
          elif [ $exitcode -eq 2 ]; then
            echo "::error::Drift detected in Staging environment!"
            exit 1
          fi
        working-directory: ./terraform/environments/staging
