name: "Terraform Plan/Apply"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  # id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  plan-dev:
    name: "Plan: Development"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform/environments/dev
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: ./terraform/environments/dev/tfplan

  apply-dev:
    name: "Apply: Development"
    runs-on: ubuntu-latest
    needs: plan-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform/environments/dev

  plan-staging:
    name: "Plan: Staging"
    runs-on: ubuntu-latest
    needs: apply-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/staging
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform/environments/staging
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-staging
          path: ./terraform/environments/staging/tfplan

  apply-staging:
    name: "Apply: Staging"
    runs-on: ubuntu-latest
    needs: plan-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/staging
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform/environments/staging

  plan-prod:
    name: "Plan: Production"
    runs-on: ubuntu-latest
    needs: apply-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/prod
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform/environments/prod
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-production
          path: ./terraform/environments/prod/tfplan

  apply-prod:
    name: "Apply: Production"
    runs-on: ubuntu-latest
    needs: plan-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/prod
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform/environments/prod
