name: "Terraform Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  basic-validation:
    name: "Basic Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Basic Tests
        run: |
          # Run terraform validate, fmt, and checkov
          # Same as your current tf-unit-test.yml

  # Run Terratest conditionally
  terratest:
    name: "Terratest (Full Integration)"
    runs-on: ubuntu-latest
    needs: basic-validation
    # Only run on:
    # - pushes to main
    # - PRs with [terratest] in title
    # - changes to critical files
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.pull_request.title, '[terratest]') ||
      contains(github.event.pull_request.title, '[full-test]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terratest
        run: |
          # Full terratest implementation
