name: "Terraform Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write

jobs:
  terraform-unit-tests:
    name: "Unit Test: ${{ matrix.environment }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, staging, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./terraform/environments/${{ matrix.environment }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/environments/${{ matrix.environment }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform/environments/${{ matrix.environment }}
          framework: terraform
